### ISSUE TITLE
table_style is not work

### ISSUE THREAD

**Issue by derekhsu** [dfop02/html4docx#6]
I set `table_style = "TableGrid" but it didn't work.

**Comment by dfop02** [comment]
Thanks for the feedback, I'll take a look this weekend

**Comment by dfop02** [comment]
Hello @derekhsu, could you please provide an small example for my tests? Where did you set the table_style?

**Comment by dfop02** [comment]
Closing the issue due to long time without response. We can reopen if necessary.
